# Path = $PRJ/.github/stale.yml

# @(#) $Id: stale.yml,v 1.1 2022/12/28 16:09:17 ralph Exp $
# -------------------------------------------------------------------------
# $Header: /home/cvs/cfg2html/cfg2html_git/.github/stale.yml,v 1.1 2022/12/28 16:09:17 ralph Exp $
# vim:ts=8:sw=4:sts=4
# coding: utf-8 -*- http://rose.rult.at/ - (c) by Ralph Roth, ROSE SWE
# -------------------------------------------------------------------------

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 180

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 45

# Issues with these labels will never be considered stale
exemptLabels:
  - Dedicated Priority Support
  - critical/security bug
  - severe improvement
  - blocker
  - bug
  - minor bug

# Label to use when marking an issue as stale
staleLabel: ready-to-close?

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
   This issue has been automatically marked as stale
   because it has not had recent activity for 180 days.
   It will be closed if no further activity occurs within 45 days.
   Thank you for your contribution.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
